[package]
name = "resume-builder"
version = "0.1.0"
authors = ["Branden Vennes <branden_vennes@trimble.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "0.3"
regex = "1"
